import pg8000.native
from urllib.parse import urlparse
from dotenv import load_dotenv
import os

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")
url = urlparse(DATABASE_URL)

conn = pg8000.native.Connection(
    host=url.hostname,
    port=url.port or 5432,
    database=url.path[1:],
    user=url.username,
    password=url.password,
    ssl_context=True
)

# Create users table
conn.run("""
    CREATE TABLE IF NOT EXISTS users (
        emp_id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        designation TEXT,
        department TEXT
    )
""")

employees = [
    ("1001", "Kalyan Sivasailam", "Chief Executive Officer", "Management"),
    ("1002", "Syed S Ahmed", "Director & Co Founder", "Management"),
    ("1003", "Mahesh Salian", "National Sales Manager", "Field Sales"),
    ("1004", "Shivaraju B", "Quality Assessor", "HIL"),
    ("1007", "Manan Nirav Reshamwalla", "Principal Product Manager", "Product"),
    ("1017", "Vaishak S", "Manager - Solutions Specialist", "Solution Specialist"),
    ("1040", "J W Rajkumar", "Lead - Quality Control", "QC"),
    ("1057", "Nawaz Sharief R", "Manager - Accounts", "Finance"),
    ("1060", "Buvaneswaran M", "Manager - Clincal AI Quality", "Pre Read"),
    ("1067", "Chethan C", "Accountant", "Finance"),
    ("1091", "Abhishek Sati", "Head of Engineering", "Engineering"),
    ("1100", "Mubarak M H", "Medical Transcriptionist", "QC"),
    ("1138", "Amith", "Lead - Application Support", "Application Support"),
    ("1141", "David Nickson", "Quality Assessor", "QC"),
    ("1142", "Shaik Ahmed", "Quality Assessor", "QC"),
    ("1146", "Sunil Kumar", "Senior Manager - Data Science", "Analytics"),
    ("1193", "Ruksana M", "Manager - Radiologist Management & Customer Support", "Rad ops"),
    ("1208", "Joel Elijah Calvin", "Senior Inside Sales Executive", "Inside Sales"),
    ("1211", "Bhavya S", "Accountant", "Finance"),
    ("1221", "Anand Iyer", "Chief Operating Officer", "Management"),
    ("1226", "Chinnasamy V", "Quality Assessor", "QC"),
    ("1228", "Nisha Chandra", "Head of IT - Security & Compliance", "IT"),
    ("1229", "Suresh Kumar C", "Quality Assessor", "QC"),
    ("1234", "Anil Kumar A", "Quality Assessor", "QC"),
    ("1243", "Chandra Thammireddy", "Quality Assessor", "QC"),
    ("1244", "Mohamed Ali S", "Quality Assessor", "QC"),
    ("1251", "Prathyusha Mannar", "Head - Human Resources", "HR"),
    ("1263", "Sachin Kumara T", "Quality Assessor", "QC"),
    ("1266", "Pooja Bai R", "Client Relationship Manager", "Key Account Management"),
    ("1274", "Nikhil Hugar", "Inside Sales Executive", "Inside Sales"),
    ("1278", "Rajendra Prasad", "Lead - Client Operations", "Enterprise Operation"),
    ("1290", "Santosh Kumar N", "Manager - Quality Control", "QC"),
    ("1293", "Kishore Prasath Venkatesh", "Head of Products", "Product"),
    ("1317", "R Keerthana", "Data Science Manager - Clinical AI", "Annotations"),
    ("1335", "Munikrishna C", "Admin/Facilities Manager", "HR"),
    ("1343", "Yogamoorthy S", "Quality Assessor", "QC"),
    ("1345", "Revathi Ezhumalai", "Manager - Clinical AI & Analysis", "Annotations"),
    ("1347", "Varshinipriya", "Lead AI Analyst", "Annotations"),
    ("1348", "Gokul Ravichandran", "Software Engineer", "Analytics"),
    ("1350", "Rajeev K", "Senior Customer Support Associate", "Customer Support"),
    ("1354", "Shalini T", "Quality Assessor", "QC"),
    ("1363", "Monashree", "Compliance Analyst", "IT"),
    ("1364", "Ganavi K", "Quality Assessor", "QC"),
    ("1366", "Abhishek Kumar Singh", "Application Support Engineer", "Application Support"),
    ("1374", "Selva Kumar B", "Quality Assessor", "QC"),
    ("1378", "Hamshavardhan S", "Quality Assessor", "QC"),
    ("1379", "Kesavaprasath M A", "Software Quality Engineer", "Engineering"),
    ("1381", "Rajaliyar Karthik", "Customer Support Associate", "Customer Support"),
    ("1395", "Ratnaprabha", "HR Executive", "HR"),
    ("1396", "Vijay S", "Data Scientist", "Analytics"),
    ("1397", "D Pavishna", "Senior AI Analyst", "Annotations"),
    ("1399", "Harini Thavamani", "Associate Product Manager", "Product"),
    ("1400", "S P Kaviya", "Senior AI Analyst", "Annotations"),
    ("1401", "Abitha Marimuthu", "Senior AI Analyst", "Annotations"),
    ("1406", "Akash Shekar", "Cyber Security Analyst", "IT"),
    ("1407", "Ummar Parish", "Application Support Engineer", "Application Support"),
    ("1411", "Mamatha", "Solution Specialist", "Solution Specialist"),
    ("1414", "Saravan Chowdary", "Inside Sales Representative", "Inside Sales"),
    ("1415", "Jebastin", "Quality Assessor", "QC"),
    ("1416", "Sindhu Lekshmi Krishna Dhas", "Quality Assessor", "QC"),
    ("1417", "K F Mohammed Rayan", "Quality Assessor", "QC"),
    ("1418", "Sajin S G", "Quality Assessor", "QC"),
    ("1419", "Rokeshkumar G", "Software Engineer", "Engineering"),
    ("1420", "Tamilarasan Palanisami", "Software Engineer", "Engineering"),
    ("1424", "Manobikash Sahoo", "Quality Assessor", "QC"),
    ("1425", "Syed Ahmed", "Radiologist Resource Coordinator", "Rad ops /Supply"),
    ("1427", "Abhisankar Biswal", "Area Sales Manager", "Field Sales"),
    ("1429", "Judy Joseph", "Patient Care Coordinator", "EVO - Medray"),
    ("1432", "Reddyvari Saiteja Reddy", "Solution Specialist", "Solution Specialist"),
    ("1434", "Trisha das", "Customer Support Associate", "Customer Support"),
    ("1435", "S Shreekara Upadhyaya", "Senior Accountant", "Finance"),
    ("1440", "Srinithi K", "AI Analyst", "Annotations"),
    ("1441", "Vasumathi R S", "AI Analyst", "Annotations"),
    ("1442", "Devika K", "AI Analyst", "Annotations"),
    ("1443", "Kishore Kumar J", "AI Analyst", "Annotations"),
    ("1444", "Sushmitha V", "AI Analyst", "Annotations"),
    ("1446", "Elakkiya R", "Associate Data Scientist", "AI Labs"),
    ("1456", "Jamesmani", "Quality Assessor", "QC"),
    ("1457", "Kirupakaran Ramesh", "Quality Assessor", "QC"),
    ("1461", "Velangani Sneha", "Accounts Executive", "Finance"),
    ("1462", "Shanmugapriyan Jagathalaprathapan", "Data Scientist", "Analytics"),
    ("1464", "Ankit Baronia", "Area Sales Manager", "Field Sales"),
    ("1467", "P Karthik", "Regional sales Manager", "Field Sales"),
    ("1472", "Swetha", "Quality Assessor", "HIL"),
    ("1473", "Kuppukannan", "Quality Assessor", "HIL"),
    ("1474", "V Mohammed Rafid", "Quality Assessor", "HIL"),
    ("1476", "Arun S", "Quality Assessor", "QC"),
    ("1480", "Harsha S", "Accounts Executive", "Finance"),
    ("1482", "Yadhavan Duraisamy", "AI Analyst", "Annotations"),
    ("1483", "Dayana", "AI Analyst", "Annotations"),
    ("1484", "Sampath Kumar D", "Inside Sales Executive", "Inside Sales"),
    ("1494", "Munna Sunny", "Solution Specialist", "Solution Specialist"),
    ("1496", "Mohamed Ibrahim Seyed Mohideen", "Quality Assessor", "Pre Read"),
    ("1498", "Gunakutti", "AI Analyst", "Annotations"),
    ("1504", "Shaik Jawadh Ali J", "Quality Assessor", "QC"),
    ("1506", "Sandesh Beejadi Sudhakar", "Manager of Strategic Alliances and Partnership", ""),
    ("1507", "Muthupidaran", "Quality Assessor", "HIL"),
    ("1512", "Rahul Asuraj Meshram", "Quality Assessor", "QC"),
    ("1513", "Shivakumar S", "Quality Assessor", "QC"),
    ("1515", "Seenamol S", "Quality Assessor", "HIL"),
    ("1516", "Sumesh Raju S", "Quality Assessor", "QC"),
    ("1518", "Mohammed Izhan Mohammed Fazal", "Customer Support Associate", "Customer Support"),
    ("1521", "Sreepriya K P", "Executive Radiology Resource Management", "Rad ops /Supply"),
    ("1522", "Mohammed Sadiq", "Executive Radiology Resource Management", "Rad ops /Supply"),
    ("1523", "Sajeer Ali Samsudeen", "Quality Assessor", "QC"),
    ("1524", "Rachepalli Chandana", "Customer Support Executive", "Customer Support"),
    ("1526", "Franklin Timmy", "Regional sales Manager", "Field Sales"),
    ("1528", "S Hariharasudhan", "Regional sales Manager", "Field Sales"),
    ("1533", "Poongovan Rangasamy", "Quality Assessor", "QC"),
    ("1534", "Dilipkumar B", "Quality Assessor", "Pre Read"),
    ("1537", "Bidyut Shit", "Quality Assessor", "QC"),
    ("1541", "Boopathy G", "Quality Assessor", "QC"),
    ("1543", "J Pavithra", "Quality Assessor", "HIL"),
    ("1544", "Shibin S", "Quality Assessor", "QC"),
    ("1545", "Mohd Danishayat Siddqui", "Regional sales Manager", "Field Sales"),
    ("1546", "Mohammed Idris", "Solution Specialist", "Solution Specialist"),
    ("1548", "Ishwar Shirish Pachpande", "Enterprise Operation Support", "Enterprise Operation"),
    ("1552", "Abhijay Subbian", "Data Scientist", "Engineering"),
    ("1553", "Karthika M", "Data Scientist", "AI Labs"),
    ("1554", "Ruthra Loganathan", "Data Scientist", "AI Labs"),
    ("1555", "Saianiruth M", "Data Scientist", "AI Labs"),
    ("1557", "GuruPrasath D", "AI Analyst", "Annotations"),
    ("1558", "Abina Sree S J", "AI Analyst", "Annotations"),
    ("1559", "Charulatha K", "AI Analyst", "Annotations"),
    ("1560", "Santhya S", "Associate Product Manager", "Product"),
    ("1561", "Athira P", "Inside Sales Executive", "Inside Sales"),
    ("1562", "Kiruthika S", "Quality Assessor", "HIL"),
    ("1563", "Kamalakannan K", "Quality Assessor", "QC"),
    ("1564", "Akash P", "Quality Assessor", "Pre Read"),
    ("1565", "Nishanth B", "Quality Assessor", "Pre Read"),
    ("1566", "Pazhaniyappan", "Quality Assessor", "Pre Read"),
    ("1569", "Johnson C", "Quality Assessor", "HIL"),
    ("1570", "Khutejatul Kubra H N", "Customer Support Executive", "Customer Support"),
    ("1571", "Shaik Baba Shohail", "Customer Support Executive", "Customer Support"),
    ("1572", "Juhi Baidya Roy", "Quality Assessor", "HIL"),
    ("1573", "Karthikeyan P S", "Quality Assessor", "HIL"),
    ("1574", "Sharanya", "Data Analyst", "Analytics"),
    ("1575", "Aswin R", "Associate Product Manager", "Analytics"),
    ("1579", "Magima Balamurugan", "Human Resource Executive", "HR"),
    ("1580", "Pera Hemanth Kumar", "Enterprise Operation Support", "Enterprise Operation"),
    ("1582", "Akhil Ananthan", "Quality Assessor", "Pre Read"),
    ("1583", "Padmadharshini Venkatesh", "Quality Assessor", "Pre Read"),
    ("1584", "Ramesh Rajendran", "Quality Assessor", "Pre Read"),
    ("1585", "Mithun Raj M", "Quality Assessor", "HIL"),
    ("1587", "Ajna Gopi M", "Quality Assessor", "QC"),
    ("1588", "Shreya S", "Compliance Analyst", "IT"),
    ("1589", "Vivek Krishnamoorthy", "Quality Assessor", "QC"),
    ("1590", "Karthick A", "Quality Assessor", "HIL"),
    ("1591", "Surendraravikumar Chollangi", "Solution Specialist", "Solution Specialist"),
    ("1593", "Abhishek Pandey", "Regional sales Manager", "Field Sales"),
    ("1594", "Anbumani Pachayappan", "Quality Assessor", "HIL"),
    ("1595", "Mohamudha Hilmiya A R", "AI Analyst", "HIL"),
    ("1596", "Sindhujaragini Kumaramangalam", "AI Analyst", "HIL"),
    ("1597", "Swetha Manivannan", "AI Analyst", "HIL"),
    ("1598", "Snowlin Jecintha M", "AI Analyst", "HIL"),
    ("1599", "Kaaviya S", "AI Analyst", "HIL"),
    ("1600", "Sivagayathri M", "AI Analyst", "HIL"),
    ("1601", "J Karunya Angeline", "AI Analyst", "HIL"),
    ("1602", "Varshini G", "AI Analyst", "HIL"),
    ("1603", "Mohammed Ashik Zameer", "IT Administrator", "IT"),
    ("1604", "Murali Sankar", "Quality Assessor", "HIL"),
    ("1605", "Kabilan", "Quality Assessor", "HIL"),
    ("1606", "Madhumitha V", "AI Analyst", "Annotations"),
    ("1607", "Rajalakshmi Rajendran", "AI Analyst", "Annotations"),
    ("1608", "Narmadha Srinivasan", "AI Analyst", "Annotations"),
    ("1609", "Manoj S", "AI Analyst", "Annotations"),
    ("1612", "K S Meenakumari", "AI Analyst", "Annotations"),
    ("1613", "Soundari S", "AI Analyst", "Annotations"),
    ("1614", "Shibu Chakraborty", "Regional sales Manager", "Field Sales"),
    ("1618", "Konduru Janapriya", "Quality Assessor", "HIL"),
    ("1619", "Shaik Karishma", "Quality Assessor", "HIL"),
    ("1620", "Vijaykumar", "Regional sales Manager", "Field Sales"),
    ("1626", "Rajat Kumar", "Inside Sales Executive", "Inside sales"),
    ("1628", "S Santhosh Kumar", "Quality Assessor", "QC"),
    ("1629", "Aswin Krishna", "Quality Assessor", "Pre Read"),
    ("1631", "Mayanapathan Nilifa", "Inside Sales Executive", "Inside Sales"),
    ("1632", "Prithesh Kothandapani Naidu", "Customer Support Executive", "Rad ops /Supply"),
    ("1633", "Mohamed Iliyas", "Quality Assessor", "HIL"),
    ("1634", "Jenifer Selvakumar", "Quality Assessor", "HIL"),
    ("1635", "Vaishnavi", "Quality Assessor", "HIL"),
    ("1636", "Dharani Raja", "Quality Assessor", "HIL"),
    ("1638", "Vikrant Prakash Kale", "Regional sales Manager", "Field Sales"),
    ("1641", "Mohanraj Kumarasamy", "Quality Assessor", "Pre Read"),
    ("1642", "Aishwarya S", "Quality Assessor", "Pre Read"),
    ("1643", "Faheem Ahad Mir", "Quality Assessor", "Pre Read"),
    ("1644", "Sivakumar A", "Quality Assessor", "QC"),
    ("1645", "Akash Ashok Chougale", "Quality Assessor", "QC"),
    ("1646", "P Samata", "Network Administrator", "IT"),
    ("1647", "Chandan K Singh", "Application Support Engineer", "Application Support"),
    ("1648", "Ambika Kotrappa Kollanavar", "Customer Support Executive", "Customer Support"),
    ("1650", "Absar Ahamath I", "Quality Assessor", "Pre Read"),
    ("1652", "Ameer", "Regional sales Manager", "Field Sales"),
    ("1653", "Mohammed Imtiyaz Ahmed", "Senior Inside Sales Executive", "Inside Sales"),
    ("1655", "Syeda Sabeela", "Customer Support Executive", "Customer Support"),
    ("1656", "Shaik Sofi Khalandar", "Customer Support Executive", "Rad ops /Supply"),
    ("1657", "M Mohamed Asik", "Quality Assessor", "Pre Read"),
    ("1660", "Saptarshi Misra", "Head Of AI & Data Science", "AI Labs"),
    ("1662", "Chutti Charan Deep", "Application Support Engineer", "Application Support"),
    ("1663", "Venkadesh B", "Quality Assessor", "Pre Read"),
    ("1664", "Safwan Siraj Mogarpane", "Application Support Engineer", "IT"),
    ("1665", "Neelakanta K N", "Senior Customer Support Executive", "Customer Support"),
    ("1666", "L P Chandan", "Senior Customer Support Executive", "Customer Support"),
    ("1667", "Abhijit Shitalkumar Shah", "Application Support Engineer", "Application Support"),
    ("1668", "Thimme Gowda G T", "Application Support Engineer", "Application Support"),
    ("1669", "Mohammad Umair Yaragatti", "Senior Inside Sales Executive", "Inside Sales"),
    ("1670", "B Dileep", "Data Analyst", "Analytics"),
    ("1671", "Keertivardhan", "Enterprise Operation Support", "Enterprise Operation"),
    ("1672", "Asim Khalifa", "Senior Inside Sales Executive", "Inside Sales"),
    ("1673", "Nanthini K", "Quality Assessor", "HIL"),
    ("1674", "Sreekonda Nivas", "Quality Assessor", "HIL"),
    ("1675", "Shaik Musa", "Quality Assessor", "HIL"),
    ("1676", "Bandi Venkata Narayani", "Quality Assessor", "HIL"),
    ("1677", "Santhosh M", "Quality Assessor", "HIL"),
    ("1678", "Vignesh S", "Quality Assessor", "HIL"),
    ("1679", "Vasudevan S", "Quality Assessor", "HIL"),
    ("1680", "Harish Nagarajan", "Quality Assessor", "HIL"),
    ("1681", "Gopika V", "Quality Assessor", "HIL"),
    ("1682", "Nelmundi Fayiza Marium", "Quality Assessor", "HIL"),
    ("1683", "Trishan Koley", "Quality Assessor", "HIL"),
    ("1684", "Mageshwaran K", "Quality Assessor", "Pre Read"),
    ("1685", "Alisha Prakash Shambharkar", "Executive Radiology Resource Management", "Rad ops /Supply"),
    ("1686", "Mohammed Faisal", "Senior Inside Sales Specialist", "Inside Sales"),
    ("1687", "Sonia Rajpal", "Regional Sales Manager", "Field Sales"),
    ("1688", "Yelugonda Ganesh Kumar", "Regional Sales Manager", "Field Sales"),
    ("1689", "Batarpali Afreen Mohammadsadiq", "Executive Radiology Resource Management", "Rad ops /Supply"),
    ("1690", "Selvarani Enssraj", "Quality Assessor", "QC"),
    ("1691", "Nikhil Kumar", "Regional Sales Manager", "Field Sales"),
    ("1692", "Subhrajit Chakraborty", "Regional Sales Manager", "Field Sales"),
    ("1693", "Vignesh R", "Senior Inside Sales Specialist", "Inside Sales"),
    ("1694", "Manikanta M", "Customer Support Executive", "Customer Support"),
    ("1695", "Himanshu Mengi", "Regional Sales Manager", "Field Sales"),
    ("1696", "Lalit Kumar", "Regional Sales Manager", "Field Sales"),
    ("1697", "Swapneel Balabhau Wakil", "Regional Sales Manager", "Field Sales"),
    ("1698", "Ayesha Siddiqa N", "Customer Support Executive", "Customer Support"),
    ("1699", "Joslina AJ", "Inside Sales Executive", "Inside Sales"),
    ("1700", "Satish Ramchandra Kambale", "Quality Assessor", "QC"),
    ("1701", "Vikraman", "Quality Assessor", "Pre Read"),
    ("1702", "Thabith Ahamed Moosa Naina", "Quality Assessor", "Pre Read"),
    ("1704", "Yadav Deepak", "Regional Sales Manager", "Field Sales"),
    ("1705", "Jana P", "Quality Assessor", "HIL"),
    ("1706", "Binod Kailash Padhy", "Regional Sales Manager", "Field Sales"),
    ("1707", "Raj Anand Tripathi", "Regional Sales Manager", "Field Sales"),
    ("1708", "Avishkar Babarao Kamble", "Software Engineer", "Engineering"),
    ("1709", "Megha Saggi", "Senior Inside Sales Executive", "Inside Sales"),
    ("1710", "H Tharini", "Inside Sales Executive", "Inside Sales"),
    ("1711", "Sandeep S Hadimani", "Quality Assessor", "Pre Read"),
    ("1712", "Koushik Kumar Saha", "Inside Sales Executive", "Inside Sales"),
    ("1713", "Mohiza Hasan Gurkar", "Inside Sales Executive", "Inside Sales"),
    ("1714", "Fiza Fathima", "IT Admin", "IT"),
    ("1715", "Kautilya Singh", "Regional Sales Manager", "Field Sales"),
    ("1716", "Abhishek Patil", "Customer Support Executive", "Customer Support"),
    ("1717", "Noor Ayesha", "Solution Specialist", "Solution Specialist"),
    ("1718", "Kundan Paswan", "Solution Specialist", "Solution Specialist"),
    ("1719", "Syed Maslihuddin Sakhaf", "Customer Support Associate", "Customer Support"),
    ("1720", "Sunil", "Senior Executive - Client Partnership", "Enterprise Operation"),
    ("1721", "Abhishek Sekar R G", "Customer Support Executive", "Customer Support"),
    ("1722", "Sriram", "Regional Sales Manager", "Field Sales"),
    ("1723", "Vishavadiya Jigar", "Regional Sales Manager", "Field Sales"),
    ("1724", "Lakhan Rameshlal Lund", "Regional Sales Manager", "Field Sales"),
    ("1725", "Sayak Kundu", "Regional Sales Manager", "Field Sales"),
    ("1726", "Syed Nowshad Ali", "Inside Sales Executive", "Inside Sales"),
    ("1727", "Sania Pathan", "Senior Inside sales Executive", "Inside Sales"),
    ("1728", "Manisha Pattnaik", "Senior Inside sales Executive", "Inside Sales"),
    ("1730", "Kartik Raghu Poojary", "Quality Assessor", "Pre Read"),
    ("1731", "Diksha Sharma", "Senior Executive Client Relationship", "Solution Specialist"),
    ("1732", "Nakul S Jayatsen", "Head Of Product", "Product"),
    ("1733", "Pradhossana Arumugam", "AI Analyst", "Annotations"),
    ("1734", "Suruthi S", "AI Analyst", "Annotations"),
    ("1735", "Shaik Gufrana Anjum Begum", "Quality Assessor", "HIL"),
    ("1736", "Keerthana Ramu", "Quality Assessor", "Pre Read"),
    ("1737", "Udhayasri V", "Quality Assessor", "Pre Read"),
    ("1738", "Sivasankari", "Quality Assessor", "Pre Read"),
    ("1739", "Subhas", "Quality Assessor", "Pre Read"),
    ("1740", "Senthammizh Selvan S", "Quality Assessor", "Pre Read"),
    ("1741", "Sivanpriyan Ruthramurthi", "Quality Assessor", "Pre Read"),
    ("1742", "Rathlavath Mallesh Nayak", "Quality Assessor", "Pre Read"),
    ("1743", "Rimon Biswas", "Regional Sales Manager", "Field Sales"),
    ("1744", "J Allapitchai", "Regional Sales Manager", "Field Sales"),
    ("1745", "Aswin N", "Regional Sales Manager", "Field Sales"),
    ("1746", "Malakari Babaleshwar", "Senior Executive - Client Partnership", "Enterprise Operation"),
    ("1747", "Alok Kumar Roy", "Junior Product Engineer", "Product"),
]

for emp in employees:
    try:
        conn.run(
            "INSERT INTO users (emp_id, name, designation, department) VALUES (:id, :n, :d, :dept) ON CONFLICT (emp_id) DO UPDATE SET name=:n, designation=:d, department=:dept",
            id=emp[0], n=emp[1], d=emp[2], dept=emp[3]
        )
        print(f"Added: {emp[1]}")
    except Exception as e:
        print(f"Error adding {emp[1]}: {e}")

conn.close()
print(f"\nDone! {len(employees)} employees seeded.")